background_opacity 0.0
background_blur 1 


# Anime Rice Look
window_padding_width 22
background_opacity 0.78
background_blur 8

window_padding_width 0


# keine Innenabstände
window_padding_width 0
window_padding_height 0

# keine Außenabstände
window_margin_width 0
window_margin_height 0
