background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 1.1
    brightness = 0.9
}

input-field {
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(ffffffaa)
    inner_color = rgba(000000aa)
    font_color = rgb(ffffff)
    fade_on_empty = false
    rounding = 12
    placeholder_text = <i>Password...</i>
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 80
    font_family = JetBrainsMono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}
